name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clippy
        working-directory: ./src-tauri
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        working-directory: ./src-tauri
        run: cargo test --verbose
